version: '3.9'   

services:
  postgres:
    image: moschopsd20/local-postgres-workspace
    container_name: local-fsdn
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
    postgres:


# run 
# docker-compose up
# su - postgres
# CREATE USER fsdn_user WITH PASSWORD 'password123';
# CREATE DATABASE fsdn;
# GRANT ALL PRIVILEGES ON DATABASE fsdn TO fsdn_user;

# stop postgresql service on windows
# Windows + R
# services.msc
# stop service